### ISSUE TITLE
help, bug ?

### ISSUE THREAD

**Issue by nyok92** [AASHISHAG/DeepSpeech-API#7]
Hi , i am trying to test deepspeech with you API but without success..
When i start recording : i've got this error on the web-console 

`AppComponent.html:6 ERROR TypeError: Cannot read property 'getUserMedia' of undefined
    at AppComponent.push../src/app/app.component.ts.AppComponent.initiateRecording (app.component.ts:42)
    at Object.eval [as handleEvent] (AppComponent.html:6)
    at handleEvent (core.js:21673)
    at callWithDebugContext (core.js:22767)
    at Object.debugHandleEvent [as handleEvent] (core.js:22470)
    at dispatchEvent (core.js:19122)
    at core.js:19569
    at HTMLAnchorElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
View_AppComponent_1 @ AppComponent.html:6
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:22729
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:14645
dispatchEvent @ core.js:19126
(anonymous) @ core.js:19569
(anonymous) @ platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:16147
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
AppComponent.html:6 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…}}`

And when i try to upload a file, i've got this result on console

`

  | defaultErrorLogger | @ | core.js:14597
-- | -- | -- | --
  | push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError | @ | core.js:14645
  | next | @ | core.js:16628
  | schedulerFn | @ | core.js:12609
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:196
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:134
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next | @ | Subscriber.js:77
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:54
  | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next | @ | Subject.js:47
  | push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit | @ | core.js:12593
  | (anonymous) | @ | core.js:16178
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:388
  | push../node_modules/zone.js/dist/zone.js.Zone.run | @ | zone.js:138
  | push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular | @ | core.js:16115
  | onHandleError | @ | core.js:16178
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError | @ | zone.js:392
  | push../node_modules/zone.js/dist/zone.js.Zone.runTask | @ | zone.js:191
  | push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:496
  | ZoneTask.invoke | @ | zone.js:485
  | timer | @ | zone.js:2054
  | setTimeout (async) |   |  
  | scheduleTask | @ | zone.js:2075
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | zone.js:407
  | onScheduleTask | @ | zone.js:297
  | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask | @ | zone.js:401
`

And Server log (backend) give me this 

`x.x.x.x - - [30/Sep/2019 09:43:41] "POST /file HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/ansible/DeepSpeech-API/backend/server.py", line 48, in post1
    username=output
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/ansible/.local/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable`

**Comment by AASHISHAG** [comment]
@nyok92 Try using [server_test.py](https://github.com/AASHISHAG/DeepSpeech-API/blob/master/backend/server_test.py). You would have to change the [dependencies ](https://github.com/AASHISHAG/DeepSpeech-API/blob/master/backend/server_test.py#L15) path.

**Comment by AASHISHAG** [comment]
@nyok92 : I hope the above solution helped. Closing the issue.
